version: "3.8"

services:
  server1: &ubuntu-server
    build: .
    ports:
      - "2221:22"

  server2:
    <<: *ubuntu-server
    ports:
      - "2222:22"

  server3:
    <<: *ubuntu-server
    ports:
      - "2223:22"

  server4:
    <<: *ubuntu-server
    ports:
      - "2224:22"

  server5:
    <<: *ubuntu-server
    ports:
      - "2225:22"